name: Terraform Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy-qa:
    name: Deploy to QA
    runs-on: ubuntu-latest
    environment: QA
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.QA_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init - QA
        run: terraform -chdir=env/QA init

      - name: Terraform Plan - QA
        run: terraform -chdir=env/QA plan

      - name: Terraform Apply - QA
        run: terraform -chdir=env/QA apply -auto-approve